# Generated by Django 4.1.3 on 2022-11-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('userid', models.CharField(max_length=20)),
                ('userpw', models.CharField(max_length=20)),
                ('useremail', models.CharField(max_length=30)),
                ('userAddress', models.CharField(blank=True, max_length=50, null=True)),
                ('userPhone', models.CharField(max_length=20)),
            ],
        ),
    ]
