# Generated by Django 4.1.4 on 2022-12-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Newsinfo",
            fields=[
                ("newsid", models.AutoField(primary_key=True, serialize=False)),
                ("cnt", models.IntegerField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("link", models.TextField(blank=True, null=True)),
                ("date_first", models.CharField(blank=True, max_length=45, null=True)),
                ("date_mod", models.CharField(blank=True, max_length=45, null=True)),
                ("newspaper", models.CharField(blank=True, max_length=45, null=True)),
                ("writer", models.CharField(blank=True, max_length=45, null=True)),
                ("context", models.TextField(blank=True, null=True)),
                ("img_link", models.TextField(blank=True, null=True)),
                ("img_alt", models.TextField(blank=True, null=True)),
                ("keyword", models.CharField(blank=True, max_length=45, null=True)),
                ("ranking", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "newsinfo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Userinfo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=20)),
                ("userid", models.CharField(max_length=20)),
                ("userpw", models.CharField(max_length=20)),
                ("useremail", models.CharField(max_length=30)),
                (
                    "useraddress",
                    models.CharField(db_column="userAddress", max_length=50),
                ),
                ("userphone", models.CharField(db_column="userPhone", max_length=20)),
            ],
            options={
                "db_table": "userinfo",
                "managed": False,
            },
        ),
    ]
